name: Deploy PDF
on:
  push:
    branches:
      - main
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Run pdflatex
     uses: xu-cheng/texlive-action@v2
     with:
       scheme: full
       run: |
         cd rules
         pdflatex battletech-outworlds-wastes.tex
         pdflatex battletech-outworlds-wastes.tex
         cd ..
         mv rules/battletech-outwords-wastes.pdf .
         rm -f .gitignore
   - name: Publish PDF
     uses: stefanzweifel/git-auto-commit-action@v5
     with:
       branch: rules-pdf
       create_branch: true
       skip_dirty_check: true
       add_options: '--force'
       commit_message: update PDF
       push_options: '--force'
       repository: 'rules'
       file_pattern: '*.pdf'
       disable_globbing: true
