name: Deploy Website
on: [push]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Run make4ht
     uses: docker://ghcr.io/michal-h21/make4ht-action:latest
     env:
       command: >
         cd rules &&
         make4ht -f html5-copy_images -j index --output-dir html --config battletech-outworlds-wastes-web.cfg battletech-outworlds-wastes-web.tex &&
         make4ht -f html5-copy_images -j index --output-dir html --config battletech-outworlds-wastes-web.cfg battletech-outworlds-wastes-web.tex &&
         make4ht -f html5-copy_images -j index --output-dir html --config battletech-outworlds-wastes-web.cfg battletech-outworlds-wastes-web.tex &&
         touch html/.nojekyll &&
         cp img/outworlds-alliance.ico html/favicon.ico &&
         echo 'outworlds-wastes.jeremylt.org' > html/CNAME
   - name: Publish Website
     uses:  peaceiris/actions-gh-pages@v3
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./rules/html
