name: Deploy Website
on: [push]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3
   - name: Run make4ht
     uses: docker://ghcr.io/michal-h21/make4ht-action:latest
     env:
       command: "cd league && make4ht -f html5-copy_images --output-dir html --config outworlds-wastes-site.cfg outworlds-wastes-site.tex && make4ht -f html5-copy_images --output-dir html --config outworlds-wastes-site.cfg outworlds-wastes-site.tex && make4ht -f html5-copy_images --output-dir html --config outworlds-wastes-site.cfg outworlds-wastes-site.tex && mv html/outworlds-wastes-site.html html/index.html && touch html/.nojekyll && echo 'outworlds-wastes.jeremylt.org' > html/CNAME && cd .."
   - name: Publish the web pages
     uses:  peaceiris/actions-gh-pages@v3
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./league/html
